networks:
  trilhos-dev-network:
    name: trilhos-dev-network

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: trilhos-next:dev
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: "1"
      WATCHPACK_POLLING: "true"
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@database:5432/${DB_NAME}
    env_file:
      - .env
    networks:
      - trilhos-dev-network
    depends_on:
      - database

  database:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    networks:
      - trilhos-dev-network

  caddy:
    image: caddy:2.11-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile.dev:/etc/caddy/Caddyfile:ro
      - caddy_data_dev:/data
      - caddy_config_dev:/config
    networks:
      - trilhos-dev-network
    depends_on:
      - web

volumes:
  pgdata_dev:
  caddy_data_dev:
  caddy_config_dev:
