networks:
  trilhos-docker-network:
    name: trilhos-docker-network

services:
  web:
    command: npm run dev -- --hostname 0.0.0.0 --port 3000
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: "1"
      CHOKIDAR_USEPOLLING: "1"
    expose:
      - "3000"
    networks:
      - trilhos-docker-network
